---
title: "07112018"
author: "Huize Zhang"
date: "07/11/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r select_data, fig.height=15}
library(readr)
library(tidyverse)
library(plyr)
match17 <- read_csv("data/2017-ausopen-matches.csv")
points17<- read_csv("data/2017-ausopen-points.csv")

dt <- left_join(points17,match17)
dt <- dt %>% mutate(Gender = as.factor(ifelse(test = match_num <2000,yes = 'Male',no = 'Female')))

# left_join: keep all the left + new from right if match 
# right_join:
# inner_join: keep the info in both 

## max(table(dt$player1))
## dt$player1
## player <- table(dt$player1)
## sort(player,decreasing = TRUE)



# gender= 1 if male, 2 if female
top_player <- function(gender,n=10){
  
  p1 <- dt %>% 
    dplyr::select(player1,Gender) %>% 
    filter(Gender == gender) %>% 
    mutate(player1 = as.factor(player1)) %>% 
    # consider each player
    group_by(player1) %>% 
    # count how many rows
    tally() %>%
    arrange(desc(n))
  
    
  p2 <- dt %>% 
    dplyr::select(player2,Gender) %>% 
    filter(Gender == gender) %>% 
    mutate(player2 = as.factor(player2)) %>% 
    # consider each player
    group_by(player2) %>% 
    # count how many rows
    tally() %>%
    arrange(desc(n))
    
    

  colnames(p1) <- c("player", "count1")
  colnames(p2) <- c("player", "count2")
  
  player<- full_join(p1,p2, by="player")
  player$count2[is.na(player$count2)] <- 0
  player$count1[is.na(player$count1)] <- 0
  
  player <- player %>% 
    mutate(count = count1 + count2) %>% 
    #select only the columns needed: player & count
    dplyr::select(player,count) %>% 
    #arrange by count
    arrange(desc(count)) %>% 
    filter(!is.na(player)) %>%   
    # select the top n as per argument 
    top_n(n)

  
  return(player)
}

male_player <- top_player("Male",20)
female_player <- top_player("Female",10)


extract_records <- function(name){
  df1 <- dt[dt$player1 == name,]
  df2 <- dt[dt$player2 == name,]
  df <- rbind(df1,df2)
  return(df)
}


RF_all <- extract_records("Roger Federer")
RF_all <- RF_all[!is.na(RF_all$match_id),]
RF_all <- RF_all %>% mutate(Position = as.integer(ifelse(player1 == "Roger Federer", 1,2))) %>% 
  arrange(match_num)
RF <- RF_all %>% filter(RF_all$ServeIndicator == RF_all$Position)
RF <- RF %>% mutate(Count = seq(1,length(RF$SetNo),1))
  



rf <- RF %>% filter(match_num == 1112)

# all matches


# issue: some player1 and player 2 are missing
# match17 %>% filter(is.na(player1))
# match17 %>% filter(is.na(player2))




# ?? history, serve width, serve depth, return depth   


```

```{r plot, fig.height=15}
library(ggplot2)
rf %>% filter(PointServer == 2) %>% dplyr::select(ElapsedTime,Speed_KMH) %>% plot()

ggplot(rf,aes(x=Count, y=Speed_KMH)) + 
  geom_point() 

ggplot(subset(rf,rf$SetNo == 4),aes(x=Count,y=Speed_KMH,col = SetNo)) +
  ylim(120,220)+
  geom_point() +
  geom_smooth(aes(group = SetNo))  


```




```{r, fig.height=15}
library(visdat)
speed <- RF$Speed_KMH[!is.na(RF$Speed_KMH)]

binomial_smooth <- function() {
  geom_smooth(method = "glm",family = "binomial",se = FALSE)
}

ggplot(RF,aes(x=Count,y=Speed_KMH,col = SetNo, group = SetNo)) +
  ylim(min(summary(speed[speed != 0])),max(summary(speed[speed != 0])))+
  geom_point() +
  facet_wrap(~match_num,ncol = 1, scales = "free_x") 
  
  
#########ignore for the time being ############
# match #1601 game 3, Federer suffered from break twice  


#####From the plot, we can see that serving speed may not necessarily indicate whether Federer is fatigue or not. In the third game of the 4th round (match #1402), Federer won consecutively 6 games against Nishikori and finished at 6:1. From the plot, his serve speed reduced from approximately 185 KMH to 165 KMH. This reduction of speed can be viewed as a strategy to save energy when Federer broke two serving games of Nishikori. Similar behaviour is also shown in match #1112, game 3,  match #1402, game 3. 

#####- May be indicator of fatigue at 1206 end of the first game 
#####3- increase of serving speed could because of multiple ADs  - strategy # 1303 game 3 (the inflection point)
#####  - but serving speed could reduce because of the same factor - # 1402, game 3 

```



